Repository santiagogubadev/iuseful-react-hooks, pull requests merged in 2025-09, with the labels that each got.

#6 Add(dependecies checker): dependabot
  .github/dependabot.yml
Labels: skip-release

#8 Hotfix/owner name
  .github/CODEOWNERS
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/documentation.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/performance.md
  .github/dependabot.yml
  LICENSE
  README.md
  package-lock.json
  package.json
Labels: minor

#17 Update: workflows
  .github/dependabot.yml
  .github/workflows/release.yml
Labels: patch

#18 Feature/coverage
  .github/workflows/ci.yml
  .gitignore
  codecov.yml
  package-lock.json
  package.json
  src/__tests__/integration/hooks/use-window-size.test.ts
  src/__tests__/unit/hooks/use-state-with-history.test.ts
  src/hooks/use-window-size.ts
  vitest.config.ts
Labels: patch

#27 Feat(hook): use hover and fix use click outside overloads
  src/__tests__/integration/hooks/use-click-outside.test.ts
  src/__tests__/integration/hooks/use-hover.test.ts
  src/hooks/use-click-outside.ts
  src/hooks/use-hover.ts
Labels: minor

#29 Fix: use hover
  src/__tests__/integration/hooks/use-hover.test.ts
  src/hooks/use-hover.ts
Labels: patch

#30 Fix: use hover
  src/hooks/use-hover.ts
Labels: patch

#31 Update use-event-listener.ts
  src/hooks/use-event-listener.ts
Labels: patch
